"""
TraceLens RAG MVP - 版本对比示例
演示如何对比两个版本的检索结果
"""
import sys
sys.path.insert(0, "..")

from uuid import UUID
from sdk.rag_client import RAGClient
from sdk.client import TraceLensClient

BASE_URL = "http://localhost:8000"


def run_rag_query(base_client, rag_client, version_id: str, query: str):
    """运行一次 RAG 查询"""
    # 1. 创建 run
    run = base_client.start_run(
        name=f"rag_query_{version_id}",
        metadata={
            "query": query,
            "version_id": version_id
        }
    )
    run_id = run.id
    print(f"\n[{version_id}] Created run: {run_id}")
    
    # 2. 模拟检索结果（不同版本可能有不同的检索结果）
    if version_id == "v1.0":
        retrieved_chunks = [
            {"chunk_id": "chunk_001", "score": 0.95, "content": "RAG stands for Retrieval-Augmented Generation..."},
            {"chunk_id": "chunk_002", "score": 0.87, "content": "RAG combines retrieval and generation..."},
            {"chunk_id": "chunk_003", "score": 0.72, "content": "The architecture of RAG includes..."},
            {"chunk_id": "chunk_004", "score": 0.65, "content": "Some unrelated content about databases..."},
        ]
    else:  # v2.0
        retrieved_chunks = [
            {"chunk_id": "chunk_001", "score": 0.92, "content": "RAG stands for Retrieval-Augmented Generation..."},
            {"chunk_id": "chunk_002", "score": 0.88, "content": "RAG combines retrieval and generation..."},
            {"chunk_id": "chunk_005", "score": 0.75, "content": "RAG improves LLM accuracy..."},
            {"chunk_id": "chunk_003", "score": 0.68, "content": "The architecture of RAG includes..."},
        ]
    
    rag_client.retrieval_completed(run_id, query, retrieved_chunks)
    print(f"[{version_id}] Reported {len(retrieved_chunks)} retrieved chunks")
    
    # 3. 上报 prompt chunks
    prompt_chunk_ids = [c["chunk_id"] for c in retrieved_chunks[:3]]
    rag_client.prompt_built(run_id, prompt_chunk_ids)
    print(f"[{version_id}] Reported {len(prompt_chunk_ids)} prompt chunks")
    
    # 4. 上报 answer
    answer = f"RAG (Retrieval-Augmented Generation) is a technique that combines retrieval and generation. (Generated by {version_id})"
    rag_client.answer_generated(run_id, answer)
    print(f"[{version_id}] Reported answer")
    
    # 5. 结束 run
    rag_client.run_finished(run_id, "success")
    print(f"[{version_id}] Run finished")
    
    return run_id


def main():
    # 初始化客户端
    base_client = TraceLensClient(BASE_URL)
    rag_client = RAGClient(BASE_URL)
    
    query = "What is RAG?"
    
    # 运行版本 v1.0
    print("=" * 60)
    print("运行版本 v1.0")
    print("=" * 60)
    run_v1_id = run_rag_query(base_client, rag_client, "v1.0", query)
    
    # 运行版本 v2.0
    print("\n" + "=" * 60)
    print("运行版本 v2.0")
    print("=" * 60)
    run_v2_id = run_rag_query(base_client, rag_client, "v2.0", query)
    
    # 获取 v1.0 的指标
    print("\n" + "=" * 60)
    print("v1.0 基础指标")
    print("=" * 60)
    metrics_v1 = rag_client.get_metrics(run_v1_id)
    print(f"metrics: {metrics_v1['metrics']}")
    
    # 获取 v2.0 的指标
    print("\n" + "=" * 60)
    print("v2.0 基础指标")
    print("=" * 60)
    metrics_v2 = rag_client.get_metrics(run_v2_id)
    print(f"metrics: {metrics_v2['metrics']}")
    
    # 对比两个版本（使用 lexical 相似度）
    print("\n" + "=" * 60)
    print("版本对比 (v2.0 vs v1.0) - lexical 相似度")
    print("=" * 60)
    diff = rag_client.get_retrieval_diff(run_v2_id, run_v1_id, similarity_mode="lexical")
    print(f"new_chunks_ratio: {diff['new_chunks_ratio']:.2%}")
    print(f"\nrank_deltas:")
    for chunk_id, delta in diff['rank_deltas'].items():
        if delta > 0:
            print(f"  {chunk_id}: +{delta} (排名下降)")
        elif delta < 0:
            print(f"  {chunk_id}: {delta} (排名上升)")
        else:
            print(f"  {chunk_id}: 0 (排名不变)")
    
    if diff.get('new_chunks_query_similarity') is not None:
        print(f"\nnew_chunks_query_similarity: {diff['new_chunks_query_similarity']:.3f}")
        print(f"dropped_chunks_query_similarity: {diff['dropped_chunks_query_similarity']:.3f}")
    
    # 使用其他相似度模式（可选）
    # print("\n" + "=" * 60)
    # print("版本对比 (v2.0 vs v1.0) - embedding 相似度")
    # print("=" * 60)
    # diff_embedding = rag_client.get_retrieval_diff(run_v2_id, run_v1_id, similarity_mode="embedding")
    # print(f"new_chunks_query_similarity: {diff_embedding['new_chunks_query_similarity']:.3f}")
    # print(f"dropped_chunks_query_similarity: {diff_embedding['dropped_chunks_query_similarity']:.3f}")
    
    print("\n" + "=" * 60)
    print("分析结论")
    print("=" * 60)
    print(f"v2.0 相比 v1.0:")
    print(f"- 新增了 {diff['new_chunks_ratio']:.0%} 的 chunks")
    if diff['rank_deltas']:
        avg_delta = sum(diff['rank_deltas'].values()) / len(diff['rank_deltas'])
        if avg_delta > 0:
            print(f"- 平均排名下降了 {avg_delta:.1f} 位")
        elif avg_delta < 0:
            print(f"- 平均排名上升了 {abs(avg_delta):.1f} 位")
        else:
            print(f"- 排名基本保持稳定")


if __name__ == "__main__":
    main()
